### ISSUE TITLE
salmon quant for paired-end reads?

### ISSUE THREAD

**Issue by DoaneAS** [nextflow-io/rnaseq-nf#1]
Hi, 

The command for salmon quantification in this pipeline is specifying single-end reads:
`salmon quant --threads $task.cpus --libType=U -i index -r $reads -o $pair_id`  

 But the pipeline seems to take paired-end reads.  
`params.reads = "$baseDir/data/ggal/*_{1,2}.fq"`    

Can you clarify please, which is it?

From the salmon manual:

```
-r [ --unmatedReads ] arg   List of files containing unmated reads (e.g. single-end reads)
-1 [ --mates1 ] arg         File containing the #1 mates  
-2 [ --mates2 ] arg         File containing the #2 mates
```

Thanks

**Comment by pditommaso** [comment]
You may be right, cc @skptic

**Comment by DoaneAS** [comment]
I'm using a command like this, for paired fastq.gz files:

```
fr1=$1
fr2=$2
pair_id=$3

salmon quant -l A -i index --threads ${NSLOTS} -o $pair_id  -1 <(gzip -cd ${fr1}) -2 <(gzip -cd ${fr2}) --numBootstraps 30
```

The NSLOTS variable is just the cores I've specified in cluster options, and is exported by SGE into the environment on a compute node.  I put the above in a bash script, and call it from the nextflow main.nf.

**Comment by skptic** [comment]
Hi @DoaneAS ,

Thanks for pointing this out, you are indeed correct.

I have updated the repo with [this](https://github.com/nextflow-io/rnaseq-nf/commit/3b5b49f4d0a3b539f1a68281995b7370bac30bd1) commit which should solve the issue.

**Comment by DoaneAS** [comment]
cheers, thanks
