### ISSUE TITLE
Issue with multiqc installation with micromamba

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/rnaseq-nf#22]
When installing with the newer micromamba-based image, the image does not work.

The installation itself succeeds, but then any `multiqc` command gives an error of missing the `typing_extensions` python module. If I manually install it in the image, it then complains about `imp`, which I am unable to fix.

A quick look at the internet suggests that `imp` has been deprecated for a while, and hence has probably been removed in newer Pythons. `importlib` should be used instead.

So I think:
- either we manage to use an older python with micromamba, or
- if only we knew the `multiqc` developer, who might look into this ... ... @ewels  ? 😊

**Comment by ewels** [comment]
It's because the container switched to Python 3.12. We already released a fix though, so either upgrade MultiQC to v1.17 or pin the Python version to 3.11.

**Comment by marcodelapierre** [comment]
Thanks Phil.

I thought I had tested 1.17 earlier today with no luck, I will re-run.

Do you know how I can pin the python version with conda/mamba?


PS to reproduce the issue, I go along the lines of: 
```
docker run --rm quay.io/nextflow/rnaseq-nf:v1.2.1 multiqc --version
```

**Comment by marcodelapierre** [comment]
I confirm 1.17 is not enough:
```
FROM mambaorg/micromamba
MAINTAINER Paolo Di Tommaso <paolo.ditommaso@gmail.com>

RUN \
   micromamba install -y -n base -c defaults -c bioconda -c conda-forge \
      salmon=1.10.2 \
      fastqc=0.12.1 \
      multiqc=1.17 \
      procps-ng \
   && micromamba clean -a -y
   #   python=3.11 \

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
USER root

```


now pinning python ...

**Comment by marcodelapierre** [comment]
and neither does this:

```
FROM mambaorg/micromamba
MAINTAINER Paolo Di Tommaso <paolo.ditommaso@gmail.com>

RUN \
   micromamba install -y -n base -c defaults -c bioconda -c conda-forge \
      salmon=1.10.2 \
      fastqc=0.12.1 \
      multiqc=1.17 \
      python=3.11 \
      procps-ng \
   && micromamba clean -a -y

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
USER root
```

will further test after the kids are in dreamland

**Comment by marcodelapierre** [comment]
All right, @ewels  so we need python 3.11 AND typing_extensions AND importlib_metadata:
```
FROM mambaorg/micromamba
MAINTAINER Paolo Di Tommaso <paolo.ditommaso@gmail.com>

RUN \
   micromamba install -y -n base -c defaults -c bioconda -c conda-forge \
      salmon=1.10.2 \
      fastqc=0.12.1 \
      multiqc=1.17 \
      python=3.11 \
      typing_extensions \
      importlib_metadata \
      procps-ng \
   && micromamba clean -a -y

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
USER root
```

**Comment by marcodelapierre** [comment]
@ewels any idea why Micromamba requires explicit mention of `importlib_metadata` ?

Without it:
```
  File "/opt/conda/lib/python3.11/site-packages/multiqc/utils/config.py", line 17, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

I am surprised, because the `setup.py` explicitly mentions it: https://github.com/ewels/MultiQC/blob/master/setup.py#l66

**Comment by ewels** [comment]
I'm at a conference today + tomorrow, but maybe @vladsavelyev can take a look?

**Comment by ewels** [comment]
Should be fixed in conda now 👍🏻
